/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.akkaserverless.hackathon.retailer

import com.akkaserverless.hackathon.item.ItemEntity
import com.akkaserverless.hackathon.item.Items
import io.cloudstate.kotlinsupport.cloudstate

class RetailerService {
    val greeting: String
        get() {
            return "Hello World - Retailer service!"
        }
}

fun main() {
    cloudstate {
        config {
            host = "0.0.0.0"
            port = 8080
            loglevel = "DEBUG"
        }
        eventsourced {
            entityService = RetailerEntity::class
            descriptor = Retailers.getDescriptor().findServiceByName("RetailerService")
            additionalDescriptors = mutableListOf(Retailers.getDescriptor(), Items.getDescriptor())
            persistenceId = "retailer"
        }
        crdt {
            entityService = ItemEntity::class
            descriptor = Items.getDescriptor().findServiceByName("ItemService")
            additionalDescriptors = mutableListOf(Items.getDescriptor())
        }
    }.start().toCompletableFuture().get()
    println(RetailerService().greeting)
}
