/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.akkaserverless.hackathon.retailer

import io.cloudstate.kotlinsupport.cloudstate

class RetailerService {
    val greeting: String
        get() {
            return "Hello World - Retailer service!"
        }
}

fun main() {
    cloudstate {
        eventsourced {
            entityService = RetailerEntity::class
            descriptor = Retailers.getDescriptor().findServiceByName("RetailerService")
            additionalDescriptors = mutableListOf(Retailers.getDescriptor())
        }
    }.start().toCompletableFuture().get()
    println(RetailerService().greeting)
}
