/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.akkaserverless.hackathon.item

import io.cloudstate.kotlinsupport.cloudstate

class ItemService {
    val greeting: String
        get() {
            return "Hello World - Item service!"
        }
}

fun main() {

    cloudstate {
        eventsourced {
            entityService = ItemEntity::class
            descriptor = Items.getDescriptor().findServiceByName("ItemService")
            additionalDescriptors = mutableListOf(Items.getDescriptor())
            persistenceId = "item"
        }
    }.start().toCompletableFuture().get()
}
