/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.akkaserverless.hackathon.item

class ItemService {
    val greeting: String
        get() {
            return "Hello World - Item service!"
        }
}

fun main() {
    println(ItemService().greeting)
}
