/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.akkaserverless.hackathon.notification

import com.akkaserverless.hackathon.notification.entities.*
import io.cloudstate.kotlinsupport.cloudstate

class PriceNotificationService {
}

fun main() {
    cloudstate {
        config {
            host = "0.0.0.0"
            port = 8080
            loglevel = "DEBUG"
        }
        eventsourced {
            entityService = RetailerEntity::class
            descriptor = PriceNotification.getDescriptor().findServiceByName("RetailerService")
            additionalDescriptors = mutableListOf(PriceNotification.getDescriptor())
            persistenceId = "retailer"
        }
        crdt {
            entityService = ItemEntity::class
            descriptor = PriceNotification.getDescriptor().findServiceByName("ItemService")
            additionalDescriptors = mutableListOf(PriceNotification.getDescriptor())
        }
    }.start().toCompletableFuture().get()
}


